import { raw } from 'hono/html';
import type { Child } from 'hono/jsx';
import { accentForeground, safeAccent } from '../lib/color';

type LayoutProps = {
  title: string;
  /** BCP-47 tag for the html lang attribute — public pages pass the customer locale */
  lang?: string;
  children: Child;
  /** 'admin' shows the nav bar; 'public' is the bare pay-page shell */
  variant?: 'admin' | 'public';
  currentPath?: string;
  /** Optional customer-facing brand accent from business settings. */
  accent?: string;
  /** Per-response CSP nonce generated by Hono secureHeaders. */
  nonce?: string;
};

const NAV_LINKS = [
  { href: '/admin', label: 'Invoices' },
  { href: '/admin/clients', label: 'Clients' },
  { href: '/admin/payments', label: 'Payments' },
  { href: '/admin/expenses', label: 'Expenses' },
  { href: '/admin/reports', label: 'Reports' },
  { href: '/admin/branches', label: 'Companies' },
  { href: '/admin/settings', label: 'Settings' },
];

export function Layout({ title, children, variant = 'admin', currentPath = '', lang = 'en', accent, nonce }: LayoutProps) {
  const brandAccent = accent ? safeAccent(accent) : undefined;
  const brandForeground = brandAccent ? accentForeground(brandAccent) : undefined;
  return (
    <>
      {raw('<!DOCTYPE html>')}
      <html lang={lang}>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{title} | Jin&amp;Jaw Invoices</title>
        {/* Admin-only theming: apply the theme cookie before the stylesheet
            paints (auto|light|dark; see :root[data-theme] in styles.css).
            Public pages never get the attribute and always render light. */}
        {variant === 'admin' ? (
          <script
            nonce={nonce}
            dangerouslySetInnerHTML={{
              __html: `(function(){var m=document.cookie.match(/(?:^|; )theme=(dark|light)/);document.documentElement.dataset.theme=m?m[1]:'auto';})();`,
            }}
          ></script>
        ) : null}
        <link
          rel="preload"
          href="/fonts/instrument-sans.woff2"
          as="font"
          type="font/woff2"
          crossorigin="anonymous"
        />
        <link rel="stylesheet" href="/styles.css" />
        {brandAccent && brandForeground ? (
          <style nonce={nonce}>
            {raw(`:root{--green:${brandAccent};--green-deep:${brandAccent};--on-accent:${brandForeground};}`)}
          </style>
        ) : null}
        <link rel="icon" type="image/png" href="/jinjaw-square.png" />
      </head>
      <body>
        {variant === 'admin' ? (
          <header class="site-header">
            <div class="container">
              <a href="/admin" class="site-brand">
                <img src="/jinjaw-square.png" alt="" class="brand-mark" />
                Jin&amp;Jaw Invoices
              </a>
              <button type="button" class="nav-toggle" id="nav-toggle" aria-label="Menu" aria-expanded="false">
                <span></span>
                <span></span>
                <span></span>
              </button>
              <nav class="site-nav" id="site-nav">
                {NAV_LINKS.map((l) => (
                  <a href={l.href} class={currentPath === l.href ? 'active' : ''}>
                    {l.label}
                  </a>
                ))}
                {/* Ends the password session, or hands off to Access's edge logout */}
                <a href="/admin/logout" class="logout">
                  Log out
                </a>
              </nav>
            </div>
          </header>
        ) : null}
        <main class={variant === 'public' ? 'pay-wrap' : 'container'}>{children}</main>
        {variant === 'admin' ? (
          <footer class="site-footer">
            Private invoicing for Jin&amp;Jaw LTD ·{' '}
            <a href="https://jin-jaw.co.uk" target="_blank" rel="noopener">
              Main website
            </a>{' '}
            · Powered by{' '}
            <a href="https://github.com/ddyy/minvoice" target="_blank" rel="noopener">
              Minvoice
            </a>
          </footer>
        ) : null}
        {variant === 'admin' ? (
          <script
            nonce={nonce}
            dangerouslySetInnerHTML={{
              __html: `
(function () {
  var btn = document.getElementById('nav-toggle');
  var nav = document.getElementById('site-nav');
  btn.addEventListener('click', function () {
    var open = nav.classList.toggle('open');
    btn.classList.toggle('open', open);
    btn.setAttribute('aria-expanded', String(open));
  });

  document.addEventListener('submit', function (event) {
    var form = event.target;
    if (!(form instanceof HTMLFormElement)) return;
    var message = form.getAttribute('data-confirm');
    if (message && !window.confirm(message)) event.preventDefault();
  });

  document.addEventListener('change', function (event) {
    var control = event.target;
    if (control instanceof HTMLSelectElement && control.hasAttribute('data-submit-on-change')) {
      control.form && control.form.submit();
    }
  });
})();
`,
            }}
          ></script>
        ) : null}
      </body>
      </html>
    </>
  );
}
